AWSTemplateFormatVersion : "2010-09-09"

Parameters:
  DynamoKey:
    Type: String
  DynamoName:
    Type: String

Resources:
  DynamoDBApp:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: !Ref DynamoKey
          AttributeType:  S
      KeySchema:
        - AttributeName: !Ref DynamoKey
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      TableName: !Ref DynamoName
      
Outputs:
  DynamoName:
    Value: !Ref DynamoDBApp
    Export:
      Name: DynamoName
  DynamoArn:
      Value: !GetAtt Dynamo.Arn
      Export:
        Name: DynamoArn

