AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    LambdaName:
        Type: String
    LambdaRuntime:
       Type: String
    LambdaBucket:
        Type: String
    ZipName:
        Type: String  
Resources:
    LambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Code:
            S3Bucket: !Ref LambdaBucket
            S3Key: !Ref ZipName
        FunctionName: !Ref LambdaName
        Handler: lambda_function.lambda_handler
        Runtime: !Ref LambdaRuntime
        MemorySize: 512
        Timeout: 600
        Role: !GetAtt LambdaRole.Arn
        Environment:
            Variables:
                DYNAMO_PLATZI: !ImportValue DynamoPlatzi

    LambdaPolicyDynamo:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    -
                      Effect: Allow
                      Action:
                          - dynamodb:PutItem
                          - dynamodb:UpdateItem
                          - dynamodb:GetItem
                          - dynamodb:*
                      Resource:
                          - "*"

    LambdaPolicyCW:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    -
                      Effect: Allow
                      Action:
                          - logs:*
                          - cloudwatch:*
                          - xray:*
                      Resource:
                          - "*"

    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        ManagedPolicyArns:
          - !Ref LambdaPolicyDynamo
          - !Ref LambdaPolicyCW
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Path: /
    LambdaPolicyS3:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    -
                      Effect: Allow
                      Action:
                          - s3:ListAllMyBuckets
                          - s3:HeadBucket
                          - s3:ListObjects
                      Resource:
                          - "*"
                    -
                      Effect: Allow
                      Action:
                          - s3:*
                      Resource:
                          - "*"                          
Outputs:
  LambdaPolicyDynamo:
    Value: !Ref LambdaPolicyDynamo
    Export:
        Name: LambdaPolicyDynamo
  LambdaPolicyCW:
    Value: !Ref LambdaPolicyCW
    Export:
        Name: LambdaPolicyCW
  LambdaFunction:
    Value: !GetAtt LambdaFunction.Arn
    Export:
        Name: LambdaFunction       
        
                       